sudo: required

services:
  - docker

before_install:
  - python .ci/check_travis_tag.py
  - docker build -t aiida_cp2k_test .
  - export DOCKERID=`docker run -d aiida_cp2k_test`

script:
  - docker exec --tty $DOCKERID wait-for-services
  - docker exec -it --user aiida $DOCKERID /bin/bash -l -c 'cd /opt/aiida-cp2k/ && pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )'
  - docker exec -it --user aiida $DOCKERID /bin/bash -l -c 'cd /opt/aiida-cp2k/ && py.test --cov aiida_cp2k --cov-append .'
  - docker exec -it --user aiida $DOCKERID /bin/bash -l -c 'cd /opt/aiida-cp2k/docs && make'

after_success:
  - docker exec -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH -it --user aiida $DOCKERID /bin/bash -l -c 'cd /opt/aiida-cp2k/ && coveralls'

after_script:
  - docker logs $DOCKERID

git:
  depth: 3

